services:
    reactapp:
        build:
            context: ./atlus
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.react-dev.rule=(Host(`localhost`) || Host(`192.168.68.62`)) && !(PathPrefix(`/api`) || Path(`/docs`) || Path(`/openapi.json`))"
            - "traefik.http.routers.react-dev.entrypoints=web"
            - "traefik.http.routers.react-dev.priority=3"
            - "traefik.http.services.react.loadbalancer.server.port=80"

    fastapiapp:
        build:
            context: ./backend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.fast-dev.rule=(Host(`localhost`) || Host(`192.168.68.62`)) && (PathPrefix(`/api`) || Path(`/docs`) || Path(`/openapi.json`))"
            - "traefik.http.routers.fast-dev.entrypoints=web"
            - "traefik.http.routers.fast-dev.priority=5"
            - "traefik.http.services.fast.loadbalancer.server.port=5000"

    rproxy:
        image: traefik:v3.0
        command:
            - "--log.level=DEBUG"
            - "--api.insecure=true"
            - "--providers.docker"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
