name: Black formatter

on:
    push:
        paths:
            - "backend/**"
            - ".github/workflows/black.yml"
    pull_request:
        paths:
            - "backend/**"
            - ".github/workflows/black.yml"
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: psf/black@stable
